"""P9 activation: three-role evidence within 60s (API path)."""

from __future__ import annotations

import time
from pathlib import Path

from fastapi.testclient import TestClient

from ilearn.api.app import create_app

ROOT = Path(__file__).resolve().parents[1]
PILOT = ROOT / "data" / "pilot"
EVIDENCE = ROOT / "runtime_evidence" / "activation_why_use.md"


def main() -> int:
    import tempfile

    tmp = Path(tempfile.mkdtemp())
    client = TestClient(
        create_app(
            sessions_dir=tmp,
            pilot_data_dir=PILOT,
            relationships_path=tmp / "relationships.json",
            llm=None,
        )
    )
    lines = ["# Activation Why-Use Evidence", "", f"Generated by `{Path(__file__).name}`", ""]
    t0 = time.perf_counter()

    qg = client.get("/quality-gates")
    assert qg.status_code == 200
    assert qg.json()["summary"]["enforced"] >= 1

    demo = client.post("/demo/units/math_5_1/session")
    assert demo.status_code == 200, demo.text
    sid = demo.json()["session_id"]
    links = demo.json().get("links") or {}

    # Student evidence: mastery public or grading receipts or diagnosis
    mastery = client.get(f"/sessions/{sid}/mastery-public")
    assert mastery.status_code == 200
    mbody = mastery.json()
    assert (
        mbody.get("evidence_count") is not None
        or mbody.get("mastery_percent") is not None
        or mbody.get("probe_gap_count") is not None
    )
    receipts = client.get(f"/sessions/{sid}/grading-receipts")
    assert receipts.status_code == 200

    # Parent evidence: action summary
    parent = client.get(f"/sessions/{sid}/summary/parent")
    assert parent.status_code == 200
    pbody = parent.json()
    assert pbody.get("action_summary") or pbody.get("weak_skills") is not None

    # Teacher evidence: tier suggestion / next_step
    teacher = client.get(f"/sessions/{sid}/summary/teacher")
    assert teacher.status_code == 200
    tbody = teacher.json()
    tier = tbody.get("tier_suggestion") or {}
    assert tier.get("next_step") or tbody.get("top_weaknesses") is not None

    # Optional assign receipt path (teacher closed loop smoke)
    assign = client.post(f"/sessions/{sid}/tiers/assign", json={})
    assert assign.status_code == 200
    assert assign.json().get("receipt", {}).get("status") == "assigned"

    elapsed = time.perf_counter() - t0
    lines.extend(
        [
            f"- session_id: `{sid}`",
            f"- elapsed_s: **{elapsed:.3f}** (budget 60)",
            f"- student: mastery-public + grading-receipts OK",
            f"- parent: action_summary/weak_skills OK",
            f"- teacher: next_step/weaknesses + tier assign OK",
            f"- quality-gates enforced: {qg.json()['summary']['enforced']}",
            f"- demo links keys: {sorted(links.keys())}",
            "",
            "Pass" if elapsed <= 60 else "FAIL over budget",
        ]
    )
    EVIDENCE.parent.mkdir(parents=True, exist_ok=True)
    EVIDENCE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"OK three-role activation in {elapsed:.3f}s session={sid}")
    return 0 if elapsed <= 60 else 1


if __name__ == "__main__":
    raise SystemExit(main())
